export const routes = {
  home: '/',
  notes: '/notes',
  note: '/notes/:id',
  words: '/words',
  word: '/words/:id',
  flashcards: '/flashcards',
  quiz: '/quiz',
  spelling: '/spelling',
  login: '/login',
  register: '/register',
  account: '/account',
  reset: '/reset-password',
  notverified: '/notverified',
  about: '/about',
};
