export const authTypes = {
  AUTH_START: 'AUTH_START',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_FAIL: 'AUTH_FAIL',
  AUTH_END: 'AUTH_END',
  CLEAN_UP: 'CLEAN_UP',
  VERIFY_START: 'VERIFY_START',
  VERIFY_SUCCESS: 'VERIFY_SUCCESS',
  VERIFY_FAIL: 'VERIFY_FAIL',
  RECOVERY_START: 'RECOVERY_START',
  RECOVERY_SUCCESS: 'RECOVERY_SUCCESS',
  RECOVERY_FAIL: 'RECOVERY_FAIL',
};
